name: CI/CD for ML Model

on:
  push:
    branches:
      - main

jobs:
  get_data:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: api 
      run: |
        python src/get_data.py

  train:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Train model
      env:
        MLFLOW_TRACKING_URI: 'https://93fd-34-29-40-242.ngrok-free.app'  
      run: |
        python src/train.py
    
    - name: Upload trained model
      uses: actions/upload-artifact@v4
      with:
        name: trained_model
        path: models/model.pkl

  test:
    needs: train
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Run unit tests
      run: |
        python tests/test.py
